### ISSUE TITLE
Flangers and Chorus blocks spawn unwanted cubes

### ISSUE THREAD

**Issue by ElectricCanary** [leoschofield/FXCoreDesigner#14]
<img width="113" alt="image" src="https://user-images.githubusercontent.com/52302192/225163231-057587f8-a8f1-4e7b-80f6-e22f8a83ad78.png">

**Comment by leoschofield** [comment]
The unwanted cubes will be for tap tempo/toggle sw ins and user outs (for LEDs) the code isn't finished yet, will close this issue when done.
